### ISSUE TITLE
requirements.txt安装报错

### ISSUE THREAD

**Issue by jzzzf** [jiahe7ay/MINI_LLM#27]
pip install -r requirements.txt时出现错误,有相同情况的吗? python版本是3.10
Collecting datasets (from -r requirements.txt (line 1))
  Using cached datasets-2.19.1-py3-none-any.whl.metadata (19 kB)
Collecting transformers==4.36.0 (from -r requirements.txt (line 2))
  Using cached transformers-4.36.0-py3-none-any.whl.metadata (126 kB)
Collecting torch==2.2.0 (from -r requirements.txt (line 3))
  Using cached torch-2.2.0-cp310-cp310-manylinux1_x86_64.whl.metadata (25 kB)
Collecting accelerate==0.27.2 (from -r requirements.txt (line 4))
  Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Collecting einops==0.7.0 (from -r requirements.txt (line 5))
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting flash-attn==2.5.5 (from -r requirements.txt (line 6))
  Using cached flash_attn-2.5.5.tar.gz (2.5 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-h9ixb2zi/flash-attn_c3250dbfc30143cdbc07d297ff096fbe/setup.py", line 9, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by boystray** [comment]
切记要先用conda install安装，这样可以自动匹配版本
https://blog.csdn.net/weixin_46443074/article/details/136615102
